### ISSUE TITLE
Showing report in frontend?

### ISSUE THREAD

**Issue by patej** [jordanlev/c5_custom_contact_form#6]
Hi Jordan,
Thanks for this package, it has been of great help!
Now I'm building an intranet type of restricted area to a site and there I use this custom form to gather some information from the users. However, I would need to get the current user's submission to show up on the same page the form is so that they could even edit it, not in Dashboard... I'm not a PHP expert, but I manage if I'm pointed to the correct direction so I'd like to know if I could use the functions like getSubmissionsForDashboardView to show the rows in the frontend? 

I have added a hidden field with the user id so it gets stored in "submitter" field and tried playing around a bit, but haven't really gotten anywhere... Just being able to duplicate the default report in the frontend would be a great beginning. I appreciate any help and tips you can give.

--patrik

**Comment by jordanlev** [comment]
Hi Patrik,
I don't think using this addon is the right solution for the situation you describe. This addon is *very* focused on the use-case of "save some form data to a table"... it has absolutely zero considerations for editing data that already exists. There are much more robust frameworks, addons and tools that are built to handle the "update existing data" use case, and you will have an easier time leveraging those instead of trying to bend this custom contact form to do something it was never meant to do.

You might want to look into some of the "advanced" form addons in the marketplace... the best case scenario is someone has already built what you need. But if not, and you want to attempt to code this on your own, it's unfortunately not something I can give a succinct answer to because you're basically asking how to build a web application -- you can certainly learn to do it and I encourage you to do so, but it requires a lot of learning and practice... not something I can impart here in a few paragraphs.

(Although I can point you to a sample Concrete5 application I use as a starting point for my own projects: https://github.com/jordanlev/c5_boilerplate_crud -- it is more focused on the dashboard, but if you want to build your own functionality on the front-end it might help you out along the way).

Good luck!

   -Jordan
